### ISSUE TITLE
Fails with kubectl not found

### ISSUE THREAD

**Issue by RichWellum** [v1k0d3n/bootkube-ci#1] opened 2017-06-02 11:12 UTC
Ran through the setup, but it failed very early on:

./bootkube-ci/bootkube-up.sh: line 199: grep: command not found
./bootkube-ci/bootkube-up.sh: line 199: grep: command not found
^C
# Looks like kubectl not found by the script:
rwellum@bootkube-ci:~$ kubectl
kubectl: command not found

What's also odd is this left my ubuntu VM in a very odd state - for example can't find basic commands like 'which' and 'grep' - but they are installed of course. So I think my VM is smoked.

**Comment by braynshock** [comment] 2017-06-02 11:38
Same happened to my OS...it blew away part of the OS. unable to login, unable to reboot.
This happened when i ran the script as root and set my BOOTKUBE_DIR to /root
I blew away OS, and started over. reading thru the script is has a number of commands that use sudo, so I assumed it needed to be run as under-privileged user.
setting BOOTKUBE_DIR to underprivileged user's home DIR, and ran as that user. (did have sudo access)
It didn't work fully, but got to step 9 before hanging.
I found that it didn't install docker, so I installed docker manually, but still can't get kubectl to start yet.

**Comment by v1k0d3n** [comment] 2017-06-02 16:02
is the script just not downloading `kubectl` @RichWellum and @braynshock? here  is the snippet:

https://github.com/v1k0d3n/bootkube-ci/blob/master/bootkube-up.sh#L150-L153

another thought is near the beginning of the script...you may run into issues if you do not have `curl` on your system. add it here:

https://github.com/v1k0d3n/bootkube-ci/blob/master/bootkube-up.sh#L30

the other thing to validate the ethernet NIC settings for the variable `$KthUBE_HW`. this is extremely important, because it's the interface that will be used to advertise the kubernetes API. here is the line you will need to validate: https://github.com/v1k0d3n/bootkube-ci/blob/master/.bootkube_env#L10

**Comment by braynshock** [comment] 2017-06-02 17:21
got it. fixed those items, got curl installed, and got ethernet interface set.

got further this time, still failing at the last step... when i check status on kubelet.service, i'm seeing errors about the localhost not responding on 443. when I check netstat i do not see anything running on 443. do you know what it's expecting to see?

**Comment by braynshock** [comment] 2017-06-02 18:18
seems to be trying to render something at line 170:
I tried to run the command manually replacing the variables:

```
braynshock@R5-Server:~/bootkube-ci$ bootkube render --asset-dir=/home/braynshock/.bootkube --experimental-self-hosted-etcd --etcd-servers=http://10.3.0.15:12379 --api-servers=https://kubernetes.default:443 --pod-cidr=10.25.0.0/16 --service-cidr=10.96.0.0/16
--experimental-self-hosted-etcd and --service-cidr set. Overriding --etcd-servers setting with [http://10.96.0.15:2379]
You have selected a non-default service CIDR 10.96.0.0/16 - be sure your kubelet service file uses --cluster-dns=10.96.0.10
Error: mkdir /home/braynshock/.bootkube: file exists
mkdir /home/braynshock/.bootkube: file exists
```
I have nothing associated with the 10.3.0.15 ip address in the command, so not sure if maybe that's hardcoded by accident also?

**Comment by braynshock** [comment] 2017-06-02 18:33
EH ok... that is not the cause of it... the errant ip i fixed, was able to render once i moved the old .bootkube dir... so moving further along in the script.

**Comment by braynshock** [comment] 2017-06-02 19:33
Kublet service isnt starting fully... this is the error in the log.

`ERROR: logging before flag.Parse: W0602 12:21:52.700932    2064 create.go:24] Unable to determine api-server readiness: Get https://kubernetes.default:443/version: dial tcp 192.168.0.135:443: getsockopt: connection refused
`

What is it expecting to see on port 443?

**Comment by v1k0d3n** [comment] 2017-06-02 19:49
yup, the order should always be to deploy (up.sh) and then tear down (clean.sh). if you do this, you should come up cleanly each time. the 443 is actually a good thing. that means that your client is waiting for containers to come online typically. you will be downloading several docker images during this long initial wait, so open another terminal and do a `watch sudo docker ps` to see images come up. in yet another terminal do a `watch kubectl get pods -o wide --all-namespaces` to see the actual kubernetes elements start to come online. this process takes a little while for your initial run (couple minutes depending on your internet speed). hope this helps @braynshock. :)

**Comment by braynshock** [comment] 2017-06-02 19:51
OK... thinking maybe it was the 17.03 version of docker might be the issue, i removed it... and let the script install docker 17.05... now the api-server is starting up.

but getting x509 error certificate error
`ERROR: logging before flag.Parse: W0602 15:50:03.719998   24523 create.go:24] Unable to determine api-server readiness: Get https://kubernetes.default:443/version: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-ca")
`

**Comment by braynshock** [comment] 2017-06-02 19:55
i get that same error running `watch kubectl get pods -o wide --all-namespaces`

still letting it run... but if i `watch sudo docker ps`

I see these:
`braynshock@R5-Server:~/bootkube-ci/log$ sudo docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
a6f1d72e08ec        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 15 minutes ago      Up 15 minutes                           k8s_POD_kube-proxy-93kql_kube-system_21171b10-47cb-11e7-a7fb-7085c23d348f_0
0ceae83b9a73        quay.io/v1k0d3n/hyperkube-amd64            "./hyperkube contr..."   16 minutes ago      Up 16 minutes                           k8s_kube-controller-manager_bootstrap-kube-controller-manager-192.168.0.135_kube-system_4e05c7e7219017f6d021ae4fc3c124e6_0
af03d074eddf        quay.io/v1k0d3n/hyperkube-amd64            "./hyperkube sched..."   17 minutes ago      Up 17 minutes                           k8s_kube-scheduler_bootstrap-kube-scheduler-192.168.0.135_kube-system_2fb43041ad0deda9c446ef31e4d18744_0
6d947c55c1fa        quay.io/v1k0d3n/hyperkube-amd64            "/usr/bin/flock --..."   18 minutes ago      Up 18 minutes                           k8s_kube-apiserver_bootstrap-kube-apiserver-192.168.0.135_kube-system_9687856c03360447b6c881a691a37290_0
5b4f454b1af8        quay.io/coreos/etcd                        "/usr/local/bin/et..."   20 minutes ago      Up 20 minutes                           k8s_etcd_bootstrap-etcd-192.168.0.135_kube-system_dc3f18ff1c2ade646beb345df5afdcd2_0
290a6a753c5b        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 22 minutes ago      Up 22 minutes                           k8s_POD_bootstrap-kube-controller-manager-192.168.0.135_kube-system_4e05c7e7219017f6d021ae4fc3c124e6_0
0fd2be0728c3        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 22 minutes ago      Up 22 minutes                           k8s_POD_bootstrap-kube-scheduler-192.168.0.135_kube-system_2fb43041ad0deda9c446ef31e4d18744_0
d16ae1f9bd42        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 23 minutes ago      Up 23 minutes                           k8s_POD_bootstrap-kube-apiserver-192.168.0.135_kube-system_9687856c03360447b6c881a691a37290_0
528d1729931c        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 23 minutes ago      Up 23 minutes                           k8s_POD_bootstrap-etcd-192.168.0.135_kube-system_dc3f18ff1c2ade646beb345df5afdcd2_0
`

**Comment by RichWellum** [comment] 2017-06-02 20:02
I usually have to do:

    mkdir -p ~/.kube
    sudo cp /etc/kubernetes/admin.conf ~/.kube/config
    sudo chown $(id -u):$(id -g) ~/.kube/config

In order to see output from kubectl

**Comment by braynshock** [comment] 2017-06-02 20:35
Thanks Rich...
where is the `tools/wait_for_kube_control_plane.sh` command supposed to be... i did a quick find and don't have a file on my system with that name.


@v1k0d3n, any idea what i need to do about the certificate error above?
Been looking at little dots filling up my screen for an hour. and still no more than the original 9 containers running. and still can't see anything when i run `watch kubectl get pods -o wide --all-namespaces`... just that x509 certificate error.

**Comment by RichWellum** [comment] 2017-06-02 20:39
You can ignore that line @braynshock - just a script to wait for the pods and I copied and pasted it from my notes. Try without - but hoping @v1k0d3n has a better answer.

**Comment by braynshock** [comment] 2017-06-02 20:48
OK... just noticed that these containers do not have an IP assigned to them...

I have a kubelet process running that contains flag pointing to /etc/cni/net.d. I do not have an /etc/cni directory.

could that be an issue?
![image](https://cloud.githubusercontent.com/assets/8523285/26744359/99176506-47b3-11e7-85b3-f9cca0f97b6c.png)

**Comment by braynshock** [comment] 2017-06-03 12:34
@RichWellum, @v1k0d3n: couple more reboots, cleans and ups, removed the `--etcd-servers=http://10.3.0.15:12379` from line 176, and added 8.8.8.8 nameserver in addition to itself in resolv.conf, and it finally produced a success message. It only took about 5 seconds to start up all the containers for step IX...
Thanks for help/info. First half dozen or so time i ran the up there was no /etc/cni/net.d... the last time i ran it, it was there... not sure if it was the changes i made or sheer dumb luck, but it's up...
Now to figure out how to work with it :)

**Comment by v1k0d3n** [comment] 2017-06-03 12:53
@RichWellum and @braynshock: i'm assuming that a couple of things that may be tripping folks up are the DNS server settings perhaps? also it concerns me a little bit that the `cp` of kubeconfig > ~/.kube/config isn't working either (is this true)? if so, i can make some adjustments on the script. if you need to make changes to this, let me know: https://github.com/v1k0d3n/bootkube-ci/blob/master/bootkube-up.sh#L214-L216

**Comment by v1k0d3n** [comment] 2017-06-03 12:54
btw, i did make some updates to the way files are downloaded to the host, and with the way `/etc/resolv.conf` is being loaded (it's a bit more idempotent i think)...i pushed these changes last night.

**Comment by braynshock** [comment] 2017-06-03 13:12
@v1k0d3n I do not have a .kube folder in the $BOOTKUBE_DIR.

i'm going to update Line 201 (should prolly be a variable from bookube_env) `--etcd-servers=http://10.3.0.15:12379` to `--etcd-servers=http://10.96.0.15:2379` and try down and up again. as my policy server is running on primary hostIP.

**Comment by v1k0d3n** [comment] 2017-06-03 13:35
ok, just pushed a change that I think should resolve this: https://github.com/v1k0d3n/bootkube-ci/blob/master/bootkube-up.sh#L215-L220

make sure to update your local git repo with these changes and let me know.

**Comment by v1k0d3n** [comment] 2017-06-03 13:37
@braynshock i really don't think line 201 is the right change here. bootkube brings up a temporary control plane, and the 10.3.0.15 address for etcd (this is the temp etcd pod) shouldn't really need changed. you should see this happening in phases:

1. temp control plane comes online
2. rendered assets start to come online
3. etcd migration starts to occur
4. once migrated, the temp control plane will be removed

one other thing...the `.kube` folder should be in your home directory.

**Comment by braynshock** [comment] 2017-06-03 15:04
@v1k0d3n - i did clean, and deleted all files... cloned repo again. Made two changes to .bootkube_env and then ran up. I now have a .kube folder, but do have this from Line201 output:
![image](https://cloud.githubusercontent.com/assets/8523285/26754615/fd936dca-484b-11e7-864b-cc193763debd.png)

If that's ok output, then ignore my L201 notes..

It was fast!
but have one error at step XI...
![image](https://cloud.githubusercontent.com/assets/8523285/26754637/6d49df3c-484c-11e7-98f2-f26e8ce249ff.png)

**Comment by v1k0d3n** [comment] 2017-06-03 15:48
yup, all that looks great @braynshock. you should have a kubernetes cluster now, correct? it is much, much faster now that i have put conditional downloads in the `up.sh` script and commented out the `rm` lines for each of the binaries.  the thought is that i want to make this flag-driven in the next week or so, in case someone wants to cache these (for CI systems like Travis), or if they want to clean them each time. the last error is fine for now. i will have this corrected in the next day or so.

one change that's coming soon is the option of using kube-router. i'll ping you about this offline later, but this is something @bzub has been pretty closely working with. it's something i think you, as a security-focused individual, should at least explore at some point as well. the project looks interesting, but requires a couple more conditionals to be optional with this repo. i'll just have to play with it some more.

**Comment by v1k0d3n** [comment] 2017-06-04 17:02
@RichWellum and @braynshock, could you guys attempt the latest version and see if this works better for you?

**Comment by braynshock** [comment] 2017-06-05 02:59
@v1k0d3n I pulled it down... it was failing on section 3: `Phase III: Preparing system DNS:
/etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf
Bootkube-CI Users: '/etc/resolv.conf is not a symbolic link' warning above is OK!`

i checked, and /etc/resolv.conf was indeed missing, created it again. re-ran the script and then completed installation.

worked for a few minutes... and now kubectl fails:
![image](https://cloud.githubusercontent.com/assets/8523285/26768958/634cd754-4979-11e7-8bf0-f6f79f9c2ec5.png)

**Comment by v1k0d3n** [comment] 2017-06-05 13:05
@braynshock: so the message (often in yellow) that states...

```
Bootkube-CI Users: '/etc/resolv.conf is not a symbolic link' warning above is OK!
```

...is reminding users that the warning above...

```
Warning: /etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf
```

...is perfectly fine. it's just a warning and should not cause you any issues. you should have a backup of your previous `resolv.conf` file located in the `backups` directory, which will be restored each time you do a `bootkube-clean.sh`. DNS is extremely important for this to work, and what the script does is put entries at HEAD and BASE, and these end up merging in `/run/resolvconf/resolv.conf`. can you verify after running the script that this file looks like:

```
cat /run/resolvconf/resolv.conf
nameserver 10.96.0.10
nameserver <your_nameserver_01>
nameserver <your_nameserver_02>
search <something_maybe> kubernetes kubernetes.default svc.cluster.local <maybe_something>
```

`something_maybe` and `maybe_something` are not really required. you just may have something there.

**Comment by braynshock** [comment] 2017-06-06 13:20
I managed to do another bootkube-clean, and up. And for the first time, I now have all kubernetes services up and running. I am going to blow away the OS, and start from base ubuntu os, and see if it works again tonight. But it's been up and running now for 12 hours, with no crashes or reboots at idle.

**Comment by v1k0d3n** [comment] 2017-06-06 23:51
perfect. i think that should do it, but let me know if you have any other issues. @RichWellum are you good now as well?

**Comment by RichWellum** [comment] 2017-06-07 02:39
Apologies @v1k0d3n - I haven't gotten back to this yet. Will probably be Friday and I'll give it another run.

**Comment by v1k0d3n** [comment] 2017-06-29 01:37
hey @RichWellum i think we've corrected any issues, but can you verify before i close out this issue?

**Comment by RichWellum** [comment] 2017-06-29 13:44
I'm trying now but I have some questions about the environment modifications needed. I think that was part of my issue before. Do you have time to walk me through it? @v1k0d3n

**Comment by v1k0d3n** [comment] 2017-07-01 03:05
@RichWellum sure. what day/time works for you? want to hit me up on kubernetes slack?

**Comment by RichWellum** [comment] 2017-07-05 12:15
@v1k0d3n Most of this week is open. I'll ping you kubernetes slack.

**Comment by v1k0d3n** [comment] 2017-07-08 18:47
@RichWellum I'm going to close this issue.  Let me know if it creeps back in, but for the most part...the repo is pretty stable now :)

**Closed as completed by v1k0d3n** 2017-07-08 18:47 UTC
